/**
 * WhatsApp Service
 * Handles the logic for generating text reports and sending them via a Gateway.
 */
const prisma = require('../config/database'); // [FIX] Singleton Prisma

const formatCurrency = (val) => {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(Number(val));
};

const WhatsAppService = {

    /**
     * Generates the "Rincian Harian" (Daily Detail) Report
     * This is sent to the Owner automatically.
     */
    async generateDailyReport(tenantId, storeId, date) {
        // 1. Fetch Aggregates (already calculated by AggregationService)
        const startOfDay = new Date(`${date}T00:00:00.000Z`);

        // Fetch Summary
        const sales = await prisma.dailySalesSummary.findFirst({
            where: { tenantId, storeId, date: startOfDay }
        });

        // Fetch Expenses (Manual Cashflow)
        const expenses = await prisma.cashflowLog.findMany({
            where: {
                tenantId,
                storeId,
                type: 'CASH_OUT',
                occurredAt: {
                    gte: startOfDay,
                    lte: new Date(`${date}T23:59:59.999Z`)
                }
            }
        });

        const totalExpense = expenses.reduce((acc, curr) => acc + Number(curr.amount), 0);

        // Fetch Kasbon (Debts Created Today)
        const debts = await prisma.debtRecord.findMany({
            where: {
                tenantId,
                storeId,
                createdAt: {
                    gte: startOfDay,
                    lte: new Date(`${date}T23:59:59.999Z`)
                }
            }
        });

        const totalDebt = debts.reduce((acc, curr) => acc + Number(curr.amount), 0);
        const netCash = (Number(sales?.netSales || 0)) - totalExpense;

        // 2. Build Text Message
        // Using simple styling typical for WhatsApp
        const reportText = `
📊 *LAPORAN HARIAN TOKO* 📊
📅 Tanggal: ${date}

*PENJUALAN*
✅ Jual Kotor: ${formatCurrency(sales?.grossSales || 0)}
✅ Transaksi: ${sales?.transactionCount || 0}
💰 *Omzet Bersih: ${formatCurrency(sales?.netSales || 0)}*

*PENGELUARAN (KAS KECIL)*
${expenses.length > 0 ? expenses.map(e => `- ${e.category}: ${formatCurrency(e.amount)} (${e.description || '-'})`).join('\n') : '- Tidak ada'}
🔻 *Total Keluar: ${formatCurrency(totalExpense)}*

*KASBON/PIUTANG*
📝 Kasbon Baru: ${formatCurrency(totalDebt)}
(${debts.length} orang)

-----------------------------
💵 *SISA KAS HARI INI: ${formatCurrency(netCash)}*
-----------------------------

_Generated by Rana POS_ 🐸
    `.trim();

        return reportText;
    },

    /**
     * Send function (Mocked for now)
     */
    async sendWhatsApp(targetNumber, message) {
        if (!targetNumber) {
            console.warn('[WA] No target number provided.');
            return;
        }

        console.log(`[WA-GATEWAY] Sending to ${targetNumber}:`);
        console.log(message);

        // In production, integrate with Twilio / Fonnte / Watzap.id here
        return true;
    }
};

module.exports = WhatsAppService;
